//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.08 at 12:31:50 AM CET 
//


package cz.spi.datamock.configuration.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.spi.datamock.configuration.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Definition_QNAME = new QName("http://datamock.spi.cz", "definition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.spi.datamock.configuration.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefinitionType }
     * 
     */
    public DefinitionType createDefinitionType() {
        return new DefinitionType();
    }

    /**
     * Create an instance of {@link SequenceStrategyType }
     * 
     */
    public SequenceStrategyType createSequenceStrategyType() {
        return new SequenceStrategyType();
    }

    /**
     * Create an instance of {@link RandomStringStrategyType }
     * 
     */
    public RandomStringStrategyType createRandomStringStrategyType() {
        return new RandomStringStrategyType();
    }

    /**
     * Create an instance of {@link DateProbabilityDistributionStrategyType }
     * 
     */
    public DateProbabilityDistributionStrategyType createDateProbabilityDistributionStrategyType() {
        return new DateProbabilityDistributionStrategyType();
    }

    /**
     * Create an instance of {@link MonthRateType }
     * 
     */
    public MonthRateType createMonthRateType() {
        return new MonthRateType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ConstantStrategyType }
     * 
     */
    public ConstantStrategyType createConstantStrategyType() {
        return new ConstantStrategyType();
    }

    /**
     * Create an instance of {@link SimpleTableStrategyType }
     * 
     */
    public SimpleTableStrategyType createSimpleTableStrategyType() {
        return new SimpleTableStrategyType();
    }

    /**
     * Create an instance of {@link RowsetType }
     * 
     */
    public RowsetType createRowsetType() {
        return new RowsetType();
    }

    /**
     * Create an instance of {@link StrategyType }
     * 
     */
    public StrategyType createStrategyType() {
        return new StrategyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datamock.spi.cz", name = "definition")
    public JAXBElement<DefinitionType> createDefinition(DefinitionType value) {
        return new JAXBElement<DefinitionType>(_Definition_QNAME, DefinitionType.class, null, value);
    }

}
